export const businessSectorMapping: Record<string, string> = {
  retail: 'Retail',
  ecommerce: 'E-commerce',
  financial_services: 'Servicios Financieros',
  insurance: 'Seguros',
  healthcare: 'Salud',
  pharmaceuticals: 'Farmacéutica',
  energy: 'Energía',
  utilities: 'Servicios Públicos',
  telecom: 'Telecomunicaciones',
  transportation_logistics: 'Transporte y Logística',
  tourism_hospitality: 'Turismo y Hospitalidad',
  education: 'Educación',
  government: 'Gobierno',
  agroindustry: 'Agroindustria',
  manufacturing: 'Manufactura',
  construction: 'Construcción',
  mining: 'Minería',
  media_entertainment: 'Medios y Entretenimiento',
  software_saas: 'Software y SaaS',
  real_estate: 'Bienes Raíces',
  food_beverages: 'Alimentos y Bebidas',
  cpg: 'Productos de Consumo',
  automotive: 'Automotriz',
  ngo: 'ONG',
  human_resources: 'Recursos Humanos',
  technology: 'Tecnología',
  consulting: 'Consultoría',
  legal: 'Legal',
  accounting: 'Contabilidad',
  marketing: 'Marketing',
  advertising: 'Publicidad',
  logistics: 'Logística',
  transportation: 'Transporte',
  hospitality: 'Hospitalidad',
  tourism: 'Turismo',
  entertainment: 'Entretenimiento',
  media: 'Medios',
  software: 'Software',
  saas: 'SaaS',
  fintech: 'Fintech',
  edtech: 'Edtech',
  healthtech: 'Healthtech',
  proptech: 'Proptech',
  cleantech: 'Cleantech',
  biotech: 'Biotecnología',
  aerospace: 'Aeroespacial',
  defense: 'Defensa',
  security: 'Seguridad',
  cybersecurity: 'Ciberseguridad',
  ai: 'Inteligencia Artificial',
  blockchain: 'Blockchain',
  cryptocurrency: 'Criptomonedas',
  gaming: 'Gaming',
  esports: 'Esports',
  fitness: 'Fitness',
  wellness: 'Bienestar',
  beauty: 'Belleza',
  fashion: 'Moda',
  luxury: 'Lujo',
  travel: 'Viajes',
  hospitality_travel: 'Hospitalidad y Viajes',
  real_estate_property: 'Bienes Raíces y Propiedades',
  construction_engineering: 'Construcción e Ingeniería',
  industrial: 'Industrial',
  chemicals: 'Químicos',
  plastics: 'Plásticos',
  textiles: 'Textiles',
  agriculture: 'Agricultura',
  forestry: 'Silvicultura',
  fishing: 'Pesca',
  food_processing: 'Procesamiento de Alimentos',
  beverages: 'Bebidas',
  tobacco: 'Tabaco',
  retail_wholesale: 'Retail y Mayorista',
  e_commerce: 'E-commerce',
  marketplace: 'Marketplace',
  platform: 'Plataforma',
  services: 'Servicios',
  professional_services: 'Servicios Profesionales',
  business_services: 'Servicios Empresariales',
  personal_services: 'Servicios Personales',
  public_services: 'Servicios Públicos',
  nonprofit: 'Sin Fines de Lucro',
  charity: 'Caridad',
  foundation: 'Fundación',
  association: 'Asociación',
  union: 'Sindicato',
  cooperative: 'Cooperativa',
  startup: 'Startup',
  scaleup: 'Scaleup',
  enterprise: 'Empresa',
  smb: 'PYME',
  sme: 'PYME',
  design: 'Diseño',
};

export const getSpanishBusinessSector = (sector: string): string => {
  return businessSectorMapping[sector.toLowerCase()] || sector;
};
